### ISSUE TITLE
3rdparty - spdlog unnecessarily forced into user code

### ISSUE THREAD

**Issue by dezed-ukaea** [FAIRDataPipeline/cppDataPipeline#19]
fdp.hxx includes spdlog header. spdlog entities required for Datapieline construction.

Loggging level provision specified via spdlog cannot be changed. Ever.

Suggets log level to be specified by a enum FairDataPipeline:log_level{ info, debug, warn ..... } etc

**Comment by dezed-ukaea** [comment]
Why expose logging interfaces to the user anyway? If they want to log something they can get their own logging API.
I suggest removing the logging API forc consumption.
Log level can still be specified via an environment variable so the public API is no longer polluted with logging classes.

**Comment by RyanJField** [comment]
This was legacy code and the spdlog can be removed.

**Comment by RyanJField** [comment]
I see this is fixed by PR #22.

**Comment by RyanJField** [comment]
Fixed by PR #22 merged 554236b
