### ISSUE TITLE
Datapipeline - log level 

### ISSUE THREAD

**Issue by dezed-ukaea** [FAIRDataPipeline/cppDataPipeline#20]
DataPipeline dp1(... log_level=debug)
DataPipeline dp2(... log_level=info)

dp1 log_level change to that of dp2

Does each instance need its own log level? Or can the global logger make do with one log level the user sets outside of the DataPipeline class
eg

fdp->set_log_level( info )
DataPipline dp1
DataPipline dp2

**Comment by dezed-ukaea** [comment]
I don't see the point in having a logging parameter in the constructor which sets the global log level. I suggest removing it from the constructor.

**Comment by RyanJField** [comment]
Agreed, there is no need for the logging level to be set in the DataPipeline constructor and can be removed.
