### ISSUE TITLE
3rdparty - ghc::filesystem::path forced upon user

### ISSUE THREAD

**Issue by dezed-ukaea** [FAIRDataPipeline/cppDataPipeline#21]
DataPipeline link_read & linw_write return ghc::filesystem::path. Is this necessary? User must adopt library. Why not return string?

**Comment by RyanJField** [comment]
Originally the API was written using C++ 17 standard and used std::filesystem::path, ghc::filesystem::path was added when the version needed to be compatible with C++ 11 to save time on refactoring.

As there are no major time constraints this dependency can be removed in favour of strings.
